name: Workflow for the RPG CI/CD

on:
  push:
    branches:
      - dev

jobs:
  testjob:
    name: Test Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_PAT }}

      - name: Run Tests
        run: python src/rpg_test.py


      - name: test_ok
       if: success()  # Ne s'exécutera que si le job 'test' réussit
        run: |
          git fetch 
          git checkout main
          git merge --ff-only origin/dev 
          git push origin main

     