name: Workflow for the RPG CI/CD

on:
  push:
    branches:
      - dev

jobs:
  testjob:
    name: Test Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_PAT }}

      - name: Run Tests
        run: python src/rpg_test.py

  push_to_main:
    needs: [testjob]
    runs-on: ubuntu-latest
    if: success()  # Ne s'exécutera que si le job 'test' réussit

    steps:
      - name: Push to main branch
        if: github.ref == 'refs/heads/dev'  # Ne s'exécutera que si la branche actuelle est 'dev'
        run: |
          git checkout main
          git pull origin main
          git push origin main

      - name: Pull from dev branch locally
        if: github.ref == 'refs/heads/dev'  # Ne s'exécutera que si la branche actuelle est 'dev'
        run: |
          git checkout dev
          git pull origin dev
