name: workflow for the rpj CI CD

on:
  push:
    branches:
      - dev

jobs:



  testjob:
    name: testjob
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: python src/rpg_test.py

  push_to_main:
    needs: [testjob]
    runs-on: ubuntu-latest
    if: ${{ needs.testjob.status == 'success' }}  # Ne s'exécutera que si le job 'test' réussit

    steps:
      - name: Push to main branch
        if: github.ref == 'refs/heads/dev'  # Ne s'exécutera que si la branche actuelle est 'dev'
        run: |
          git checkout main
          git pull origin main
          git push origin main

      - name: Pull from dev branch locally
        if: github.ref == 'refs/heads/dev'  # Ne s'exécutera que si la branche actuelle est 'dev'
        run: |
          git checkout dev
          git pull origin dev
