name: Workflow for the RPG CI/CD

on:
  push:
    branches:
      - dev

jobs:
  test_and_push:
    name: Test and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Run tests
        run: python src/rpg_test.py

      - name: Git fetch
        run: git fetch

      - name: Checkout main branch
        run: git checkout main

      - name: Merge dev branch into main
        run: git merge --ff-only origin/dev

      - name: Push to main branch
        run: git push origin main
